### ISSUE TITLE
Labwc-tweaks gtk

### ISSUE THREAD

**Issue by letkan** [labwc/labwc-tweaks#42]
Any chance of keeping the previous gtk based app alive? I haven't seen in this Qt based one any option for changing the gtk theme as in the gtk version, not to mention that it breaks visual integration with the rest of the apps I'm using.

**Comment by Consolatis** [comment]
For the moment you could use
- #43

and then build with `meson setup build && meson compile -C build`, that should give you the GTK version (without a matching `.desktop` file though).

For the longer term that is something that @johanmalm can comment on.
I imagine having both - GTK and Qt - frontends around might be hard to maintain.

**Comment by johanmalm** [comment]
> Any chance of keeping the previous gtk based app alive?

Yes.

Just to be clear though, I'm not spending much time on `tweaks` and find Qt easier to develop in, so may not move the Gtk version forward at all. It really needs a Glade `.ui` file and ideally upgrade to Gtk4, but given a pretty tight "time-budget" I found it too big a step with no Glade support for Gtk4 and very few Gtk4 examples in C.

I'll keep it alive in the repository and will of course accept patches if anyone feels like working on it.

> I haven't seen in this Qt based one any option for changing the gtk theme as in the gtk version

Yes, removed the gsettings calls from the Qt version; mostly to try to create some nicer separation lines (i.e. just be a configuration tool for `rc.xml` and `environment` rather than any GUI toolkits that DEs may or may not want to setup using different tools.

TBH though, I'm not sure we've quite hit the spot for this in terms of a scope that feels just right.

I intend to let both version gradually develop as I (and whoever wants to join) find inspiration to add/fix/extend. As I said, personally I'll be working on the Qt version.

I'm content that the two version take different directions.

> not to mention that it breaks visual integration with the rest of the apps I'm using.

Yes, that is indeed a consideration.

In fact, the scope dilemma described above is probably due to difficulty in settling on a target audience. Up until now it's just been whatever I found useful to test the compositor and it sort of just followed my mood. I do think though that it's likely to be more useful to more people if the scope is a bit smaller and more focused on the compositor as DEs (and people who just build their own setups) probably have other tools for tweaking things like Gtk themes and may therefore find the overlapping scope unattractive.

Welcome thoughts from @redtide who has been working on a gtk configuration tool.

Also - @spl237 @01micko - any preference in direction or thoughts on this?

**Comment by spl237** [comment]
I've never used this - will have to try it. We have a couple of nice GUI tools for customisation of the RPi Desktop, which I have modified where appropriate for labwc - see https://github.com/raspberrypi-ui/rc_gui and https://github.com/raspberrypi-ui/appset

My preference would be for GTK over Qt, as the vast majority of RPi Desktop uses GTK, and the few bits that do use Qt cannot be made to look completely identical, much as I have tried to do so!

**Comment by redtide** [comment]
> Welcome thoughts from @redtide who has been working on a gtk configuration tool.

Thank you!

IMO the GTK/Meson version should be kept alive in its own fork, say "labwc-tweaks-gtk"? So who maintain that fork can choose if to keep the GTK settings as well.

What I can say about the GTK over Qt? I was using LXDE, based on GTK2. At some point GTK2 was too old and I saw they tried to port it to GTK3, then chosen Qt because more lightweight. If that's true I don't see why prefer GTK3 over Qt for RPi; I use LXQt on ArchlinuxARM in my Odroid N2+. Anyway in the end it's also a matter of taste.

**Comment by 01micko** [comment]
I think the gtk version should mirror the qt version. I haven't looked at the qt version yet but the only thing that should really stay from the `gsettings` is cursor themes.

**Comment by spl237** [comment]
> What I can say about the GTK over Qt? I was using LXDE, based on GTK2. At some point GTK2 was too old and I saw they tried to port it to GTK3, then chosen Qt because more lightweight. If that's true I don't see why prefer GTK3 over Qt for RPi.

I myself ported LXDE to GTK3 from GTK2 - by then the maintainers had lost interest anyway. The version of LXDE which we ran on Pi prior to Wayland (and indeed still run on older versions of the Pi which don't support Wayland) is completely GTK3-based.

For me, GTK has the advantage over Qt that more apps seem to use it, which means sticking with it is better for consistency. I would need to rewrite several large pieces of software to move to Qt, and I don't see any advantage of Qt over GTK to make it worthwhile doing so. Also, from a themeability point of view, GTK is better than Qt, and also it has some nice UI features, such as auto-hiding shortcut indicators, which Qt lacks.

On Pi, we will be sticking with GTK for the foreseeable future for all new and existing development work. If we commission new third-party work, I always insist that it is GTK based.

**Comment by redtide** [comment]
> I haven't looked at the qt version yet but the only thing that should really stay from the `gsettings` is cursor themes.

currently tweaks' cursor settings are based on Labwc' XCURSOR_{THEME|SIZE} environment variables. Unless you want Labwc depending from GLib/GTK, if you want use GSettings then you open a door to configure all toolkits/DEs around, which would be a real mess. For this reason I made my own "GTK Settings" app (in Qt! :smile:) as separated config tool.

**Comment by johanmalm** [comment]
Have created https://github.com/labwc/labwc-tweaks-gtk
