### ISSUE TITLE
Wrong name in desktop file.

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc-tweaks#49]
Is `labwc-tweaks`.

Should be `Labwc Settings`.

I blocked translations atm.

![immagine](https://github.com/labwc/labwc-tweaks/assets/10681413/765aaf47-5185-4f4c-a49a-798d8fee2615)

**Comment by redtide** [comment]
Again this discussion? What is wrong with the name of the application and why block the translations?

**Comment by stefonarch** [comment]
Also  "Labwc Tweaks" is fine to me - but in any menu you won't find a lowercase app like "labwc-tweaks", also sddm-conf and picom-conf do not have their appname in the menu.

I blocked the translations to prevent double work for translators.

**Comment by redtide** [comment]
I think there are errors all around on this context on other applications.

I have some applications installed with lowercase names: drawio, synthv1, x42-whirl, nomacs, nheko, kitty, qps (...) and ranger (text based file manager). 

I followed some other namings when doing picom-conf and sddm-conf, but I see there are wrong ones elsewhere. So in this case the wrong thing is the Italian translation I used for the name.

In some applications I see that the name is, IMO correctly, not translated because it's really the name of the application, there have been some changes somewhere to favor generic namings in menu but it's against the spec. Names are names, Firefox, Filezilla, Geany. Generic are Web Browser, FTP Client and Text Editor. Plus the comment is really a brief description.

I would like once for all to use the correct namings to follow the spec but this is not my app.
@johanmalm what do you think? This was discussed already somewhere.

**Comment by stefonarch** [comment]
I ran through "All applications" in the LXQt menu and found only qps, nheko and colorpicker lowercase besides qBittorrent and aMula and no hyphens.

**Comment by johanmalm** [comment]
I prefer "Labwc Tweaks"
